#!/usr/bin/env bash
# Script to transfer a file from client to the server

# check if number of arguments is >=3

if [ $# -ge 3 ]
then
	if [ $# -eq 3 ]
	then 
		# No private key for connection provided
		scp -o StrictHostKeyChecking=no $1 $3@$2:~/
	else
		# Private key provided
		scp -i "$4" -o StrictHostKeyChecking=no $1 $3@$2:~/
	fi
else
	echo "Usage: $0  PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
