#!/usr/bin/env bash
# Redirection script 

apt-get -y install nginx 
ufw allow 'Nginx HTTP'

#Override the default index file 
echo "Hello User" >> /var/www/html/index.html


# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure NGINX to use the custom 404 page
# Modify the default server block in the NGINX configuration
sed -i '/server_name _;/a \    error_page 404 /404.html;\n    location = /404.html {\n        internal;\n    }' /etc/nginx/sites-available/default

# Step 5: Restart NGINX to apply changes
service nginx restart
